let skillsbuild = require("./Images/skillsbuild.png");
let watson = require("./Images/watson.png");
let mindspark = require("./Images/mindspark.png");
let developer = require("./Images/developer.png");

export const courseData = [
    {"id": "001",
    "name":"IBM SkillsBuild - Artifical Intelligence",
    "description":"The IBM SkillsBuild page for Artificial Intelligence, containing the courses, software, and resources needed for your learning journey.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":[],
    "postreq":[101,102,103,104],
    "difficulty":1,
    "terms":["AI","Software","Resources","Basics","Skills","IBM"],
    "link":"https://www.ibm.com/academic/topic/artificial-intelligence"},
    
    {"id": "002",
    "name":"Watson Academy",
    "description":"A collection of over 100 self-paced online courses teaching you to use Watson AI for a variety of purposes.",
    "duration":-1,
    "image": watson,
    "prereq":[101,301],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Watson","Studio","Machine Learning","Natural Language Processing","Cloud","Data","Basics","IBM"],
    "link":"https://www.ibm.com/training/watson"},
    
    {"id": "003",
    "name":"Mindspark AI Education",
    "description":"An online professional learning suite of free live and on-demand webinars, crafted by and for educators. Features nine webinars which will guide educators through AI’s foundational concepts.",
    "duration":-1,
    "image":mindspark,
    "prereq":[],
    "postreq":[301,302,303,304,305,306,307,308,309],
    "difficulty":1,
    "terms":["AI","Teaching","Education","Students","School","Basics","Ethics","Humans","Inclusivity"],
    "link":"https://www.mindspark.org/ibm-ai"},
    
    {"id": "004",
    "name":"IBM Developer",
    "description":"Learn in-demand skills, build solutions with real sample code, and connect with a global community of developers.",
    "duration":-1,
    "image":developer,
    "prereq":[],
    "postreq":[],
    "difficulty":3,
    "terms":["AI","Development","Software","Machine Learning","Deep Learning","Programming","Languages","Application Modernization","Messaging","IBM"],
    "link":"https://developer.ibm.com/"},
    
    {"id": "101",
    "name":"Getting Started with Enterprise-grade AI",
    "description":"This course covers the foundations of Artificial Intelligence for business, including the following topics: AI Evolution, AI Industry Adoption Trends, Natural Language Processing and Virtual Agents.",
    "duration":5,
    "image":skillsbuild,
    "prereq":[],
    "postreq":[102,103,104],
    "difficulty":1,
    "terms":["AI","Business","Industry","Natural Language Processing","Foundation","Evolution","Watson","Basics","Chatbot"],
    "link":"https://keyskill-clms.comprehend.ibm.com/course/view.php?id=236"},

    {"id": "102",
    "name":"IBM Watson Machine Learning Essentials",
    "description":"Watson Machine Learning is a service on IBM Cloud with features for training and deploying machine learning models and neural networks. This course consists of a series of videos showing how to use the Watson Machine Learning in Watson Studio.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":[101],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Watson","Cloud","Neural Networks","Videos","Machine Learning","Data"],
    "link":"https://learn.ibm.com/course/view.php?id=4482"},
    
    {"id": "103",
    "name":"Data Refinery Essentials",
    "description":"Data Refinery is a self-service data preparation client for data scientists, data engineers, and business analysts. With it, you can quickly transform large amounts of raw data into consumable, quality information that’s ready for analytics.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":[101],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Watson","Data","Refinery","CSV","Raw"],
    "link":"https://learn.ibm.com/course/view.php?id=4480"},
    
    {"id": "104",
    "name":"IBM Watson Knowledge Catalog Essentials",
    "description":"IBM Watson Knowledge Catalog is a secure enterprise catalog to index, classify, and govern your data with greater efficiency. Manage your data from every angle giving you a 360-degree view of your data so you can create models, uncover insights, and collaborate more effectively.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":[101],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Watson","Data","Catalogue","Analysis","Assets","Profiling","Classification"],
    "link":"https://learn.ibm.com/course/view.php?id=4481"},
    
    {"id": "301",
    "name":"Creating a Spark for Artificial Intelligence",
    "description":"An online introductory webinar designed primarily for teachers. Provides the knowledge and confidence needed to introduce younger students to the basics of AI.",
    "duration":0,
    "image":mindspark,
    "prereq":[],
    "postreq":[302],
    "difficulty":1,
    "terms":["AI","Teaching","Introduction","Students","Neural Network","Data","Algorithm","Machine Learning","Play","Activities","Inspire"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence"},
    
    {"id": "302",
    "name":"AI Here, AI There… AI Who, What, Where?",
    "description":"An online webinar designed primarily for teachers. Provides the knowledge needed to teach students to solve real-world problems using AI.",
    "duration":0,
    "image":mindspark,
    "prereq":[301],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Teaching","Students","Application","Real-Life","Game","Videos","Activity","Data"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m"},
    
    {"id": "303",
    "name":"Ethics in AI - Can You Crack the Moral Code?",
    "description":"An online webinar designed primarily for teachers. Explores the ethical dilemmas through discussions and activities, including words from an IBM AI expert.",
    "duration":0,
    "image":mindspark,
    "prereq":[301],
    "postreq":[304],
    "difficulty":2,
    "terms":["AI","Teaching","Students","Ethics","Morality","Discussion","Activity","Expert"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj"},
    
    {"id": "304",
    "name":"AI Can and Should be Inclusive – Design Thinking Can Help!",
    "description":"An online webinar designed primarily for teachers. Grow your understanding of AI through the lens of equity-centered design thinking, then return to the classroom with tools to encourage students to examine and address their own biases.",
    "duration":0,
    "image":mindspark,
    "prereq":[303],
    "postreq":[309],
    "difficulty":2,
    "terms":["AI","Teaching","Students","Inclusivity","Equality","Equity","Bias","Activity"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6"},
    
    {"id": "305",
    "name":"How Do Siri, Alexa and Watson Understand Me?",
    "description":"An online webinar designed primarily for teachers. Learn to understand the complexities of human language - and what it takes for a computer to understand us! See examples of how NLP can be used for social good, and get students thinking about other applications of this powerful technology.",
    "duration":0,
    "image":mindspark,
    "prereq":[301],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Teaching","Students","Natural Language Processing","Speech","Siri","Alexa","Real-Life","Social"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8"},
    
    {"id": "306",
    "name":"Machines Can Learn – But They Need Our Help!",
    "description":"An online webinar designed primarily for teachers. Take part in a larger discussion around intelligence, then learn more specific subsets of machine learning by comparing them to how students learn in the classroom.",
    "duration":0,
    "image":mindspark,
    "prereq":[],
    "postreq":[],
    "difficulty":1,
    "terms":["AI","Teaching","Students","Machine Learning","Intelligence","Activity","Thought Experiment"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-lw8fp"},
    
    {"id": "307",
    "name":"Amplifying Human Potential - Beyond Programming and Coding",
    "description":"An online webinar designed primarily for teachers. Examines the function of robots in enterprise, what makes a robot artificially intelligent, and how students can be taught to program their own robot",
    "duration":0,
    "image":mindspark,
    "prereq":[],
    "postreq":[],
    "difficulty":1,
    "terms":["AI","Teaching","Students","Robot","Robotics","Real-Life","Activity","Programming"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7"},
    
    {"id": "308",
    "name":"AI and Your Curriculum - The Perfect Marriage",
    "description":"An online webinar designed primarily for teachers. Understand the effect AI is having on the future of work, and the skills needed to be successful. Build these employability skills in students to prepare them for anything. Practice these skills with IBM’s “Machine Learning for Kids” Scratch project.",
    "duration":0,
    "image":mindspark,
    "prereq":[301],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Teaching","Students","Classroom","Employability","Skills","Work","Scratch","Machine Learning"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7-36c99"},
    
    {"id": "309",
    "name":"Building a Culture of Inclusivity",
    "description":"An online webinar designed primarily for teachers. Examine your own tech experience as you explore the roles of gender, race, and bias in technology and STEM fields. Gain the resources needed to make your students aware of how AI affects them, and join the fight against algorithmic bias and injustice.",
    "duration":0,
    "image":mindspark,
    "prereq":[304],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Teaching","Students","STEM","Diversity","Inclusion","Gender","Race","Bias","Algorithm"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7-36c99-88r6j"},
    
    {"id": "401",
    "name":"Implement trustworthy AI and data governance on AWS using IBM Cloud Pak for Data",
    "description":"Learn step-by-step how to streamline data integration, data governance, analytics, and data virtualization on AWS.",
    "duration":5,
    "image":developer,
    "prereq":[103],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Data","AWS","Amazon","SageMaker","Pandemic","Analytics","Analysis","Virtualisation","Bias","Machine Learning"],
    "link":"https://developer.ibm.com/learningpaths/pandemic-management-system-aws-ibm-cloud-pak-for-data/"},
    
    {"id": "402",
    "name":"Get started with deep learning",
    "description":"Explore this branch of machine learning that's trained on large amounts of data and deals with computational units working in tandem to perform predictions.",
    "duration":2,
    "image":developer,
    "prereq":[101],
    "postreq":[],
    "difficulty":2,
    "terms":["AI","Data","Machine Learning","Deep learning","Prediction","Architecture","Python","TensorFlow"],
    "link":"https://developer.ibm.com/learningpaths/get-started-with-deep-learning/"},
    
    {"id": "403",
    "name":"Get started with machine learning",
    "description":"Designed for anyone interested in quickly getting up to speed with machine learning. Consists of step-by-step tutorials with hands-on demonstrations where you will build models and use them in apps.",
    "duration":2,
    "image":developer,
    "prereq":[],
    "postreq":[401,402],
    "difficulty":1,
    "terms":["AI","Machine Learning","Scikit","Classification","Regression","Python","Supervised","Unsupervised","Data"],
    "link":"https://developer.ibm.com/learningpaths/learning-path-machine-learning-for-developers/"}
];